version: 2

models:

  # =====================================================================
  #                           STAGING MODEL: stg_accounts
  # =====================================================================
  - name: stg_accounts
    description: >
      Staging model containing the latest version of each account after
      deduplication. Serves as the source of truth for account attributes.
    config:
      tags: ['staging']
      meta:
        owner: 'data-engineering'
        layer: 'staging'

    columns:
      - name: account_id
        description: Primary key for the account.
        tests:
          - unique
          - not_null

      - name: customer_id
        description: Foreign key referring to the customer entity.
        tests:
          - not_null

      - name: account_type
        description: Type of account (checking, savings, or loan).
        tests:
          - accepted_values:
              values: ['checking', 'savings', 'loan']

      - name: balance
        description: Current balance associated with the account.
        tests:
          # Type validation
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: NUMERIC

          # Balance cannot be less than -5000
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -5000
              strictly: false

      - name: created_at
        description: Timestamp when the account was created.
        tests:
          - not_null


  # =====================================================================
  #                           FACT MODEL: fct_transactions
  # =====================================================================
  - name: fct_transactions
    description: >
      Fact table containing all financial transactions for accounts.
      This is an incremental model supporting MERGE logic on transaction_id.
    config:
      tags: ['fact', 'finance']
      meta:
        owner: 'data-engineering'
        layer: 'mart'
        grain: 'transaction_id'

    columns:
      - name: transaction_id
        description: Primary key for the transaction record.
        tests:
          - unique
          - not_null

      - name: account_id
        description: Account related to the transaction.
        tests:
          - not_null
          - relationships:
              to: ref('stg_accounts')
              field: account_id

      - name: customer_id
        description: The customer owning the related account.
        tests:
          - not_null

      - name: amount
        description: Amount of the transaction.
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -100000
              max_value: 100000
              strictly: false

      - name: transaction_time
        description: Timestamp when the transaction occurred.
        tests:
          - not_null

      - name: created_at
        description: Timestamp when this transaction was processed and loaded.
        tests: []
