version: 2

models:
  # -------------------------------------------------------------------------
  # STAGING MODEL: stg_accounts (Source for current, latest account data)
  # -------------------------------------------------------------------------
  - name: stg_accounts
    description: Deduplicated, latest account record from the raw accounts data source.
    columns:
      - name: account_id
        description: Primary key for the account.
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: Foreign key link to the customer dimension (if you have one).
        tests:
          - not_null
          
      - name: account_type
        description: Type of account (e.g., 'checking', 'savings').
        tests:
          - accepted_values:
              args:
                values: ['checking', 'savings', 'loan']
                
      - name: balance
        description: Current account balance.
        tests:
          # FIX: Using dbt_expectations tests with the required 'args' key
          - dbt_expectations.expect_column_values_to_be_of_type:
              args:
                column_type: NUMERIC
          # Allow some negative balance/overdraft, but enforce a reasonable lower bound
          - dbt_expectations.expect_column_min_to_be_greater_than:
              args:
                min_value: -5000 
                
      - name: created_at
        description: Timestamp when the account was initially created.
        tests:
          - not_null
          
  # -------------------------------------------------------------------------
  # FACT MODEL: fct_transactions (Incremental Transactional Data)
  # -------------------------------------------------------------------------
  - name: fct_transactions
    description: Consolidated and joined transaction facts (incremental merge).
    columns:
      - name: transaction_id
        description: Primary key for the transaction.
        tests:
          - unique
          - not_null
          
      - name: account_id
        description: Foreign key to the account table.
        tests:
          - not_null
          # Enforce Referential Integrity: All transaction accounts must exist in stg_accounts
          - relationships:
              args:
                to: ref('stg_accounts')
                field: account_id
                
      - name: customer_id
        description: Customer ID derived from joining the account staging table.
        tests:
          - not_null # Should always be present due to the JOIN on stg_accounts
          
      - name: amount
        description: Transaction amount.
        tests:
          # Ensure amounts are within a plausible range for a single transaction
          - dbt_expectations.expect_column_min_to_be_greater_than:
              args:
                min_value: -100000 
          - dbt_expectations.expect_column_max_to_be_less_than:
              args:
                max_value: 100000
                
      - name: transaction_time
        description: The time the transaction occurred.
        tests:
          - not_null